# Generated by Django 5.0 on 2025-08-03 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_cat_name', models.CharField(max_length=100, unique=True)),
                ('cat_slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('cat_image', models.ImageField(blank=True, null=True, upload_to='ecommerce/category_images/')),
                ('description', models.TextField(blank=True, null=True)),
                ('cat_ordering', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Product Categories',
                'db_table': 'product_category',
                'ordering': ['-is_active', 'cat_ordering'],
            },
        ),
        migrations.CreateModel(
            name='ProdutSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_cat_name', models.CharField(max_length=100, unique=True)),
                ('sub_cat_slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('sub_cat_image', models.ImageField(blank=True, null=True, upload_to='ecommerce/subcategory_images/')),
                ('sub_cat_ordering', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory_created_by', to=settings.AUTH_USER_MODEL)),
                ('main_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='ecomapp.productmaincategory')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategory_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Product Sub Categories',
                'db_table': 'product_subcategory',
                'ordering': ['-is_active', 'sub_cat_ordering'],
            },
        ),
    ]
