# Generated by Django 5.0 on 2025-08-03 12:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0002_productmaincategory_produtsubcategory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProdutSubCategory',
            new_name='ProductSubCategory',
        ),
    ]
